server:
  port: 9696
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: sa
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    password: Aug@1996
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: harivinodkrishna@gmail.com
